# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f9ef69a4a2434f95a1292c21b8ee04e04fd610d9345d9ce5a4587700a02369287681cc5c6b6113a76376b564bf9e81ff87007faf4d0c8fad6c70be4685ecd97

test:
  secret_key_base: af0d4f1809d3c7f2e381d394f1cab9cc0acefc0cece3efb67adeb104fc7dcd28a7b54eb666ca0dedba404ddfc9ba5e47de522b3003ceefd59e1e43a622823b03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
